# Generated by Django 4.2.7 on 2024-03-17 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeNumber',
            fields=[
                ('badge_no', models.DecimalField(decimal_places=0, help_text='Enter a valid Badge Number', max_digits=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter a valid First Name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid Last Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCollection',
            fields=[
                ('case_id', models.CharField(help_text='Enter a valid Case Identifier', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('case_description', models.CharField(help_text='Enter a valid Case Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_name', models.CharField(help_text='Enter The County', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentNumber',
            fields=[
                ('dep_no', models.CharField(help_text='Enter a valid Department Number', max_length=10, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(help_text='Enter a valid First Name', max_length=200)),
                ('dep_head', models.CharField(help_text='Enter a valid Last Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enforcer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('badge_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.badgenumber')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('unique_id', models.CharField(help_text='Enter a valid Suspect Unique Identifier', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text='Enter a valid First Name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid Last Name', max_length=200)),
                ('gender', models.CharField(help_text='Enter a valid Gender', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Enter a valid Date of Birth', null=True)),
                ('age', models.CharField(help_text='Enter a valid Age', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuspectResponse',
            fields=[
                ('testification_id', models.AutoField(help_text='Enter a valid testification id', primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, help_text='Auto-generated serial number', max_length=8, unique=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('trace', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Any strong Trace of Suspect in Crime Scene?', max_length=3)),
                ('know_complainant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Know complainant?', max_length=3)),
                ('involved_with_complainant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Involved with complainant?', max_length=3)),
                ('recidivist', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Involved in similar case?', max_length=3)),
                ('case_description', models.ForeignKey(help_text='Enter a valid Case description', on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('unique_id', models.ForeignKey(help_text='Enter a valid Suspect Identifier', on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.suspect')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_code', models.CharField(choices=[('SEC45', 'SEC45'), ('SEC67', 'SEC67'), ('SEC79', 'SEC79')], help_text='Security Code ?', max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('news_header', models.CharField(help_text='Enter a Your News Header', max_length=50, unique=True)),
                ('news_body', models.CharField(help_text='Enter a Your News Body', max_length=250, unique=True)),
                ('county', models.ForeignKey(help_text='Enter a Your News County', on_delete=django.db.models.deletion.CASCADE, to='peace.county')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, help_text='Date of submission')),
                ('feedback', models.CharField(choices=[('Doubt', 'Doubt'), ('Correct', 'Correct')], help_text='Feedback Type ?', max_length=10)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.suspectresponse')),
            ],
        ),
        migrations.CreateModel(
            name='EnforcerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badeg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.enforcer')),
                ('case_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.case')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('dep_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peace.departmentnumber')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peace.casecollection'),
        ),
    ]
