# Generated by Django 4.2.7 on 2024-03-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='county',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
