# Generated by Django 4.2.7 on 2024-03-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0002_remove_new_county_delete_feedback_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectresponse',
            name='query1',
            field=models.CharField(default='', help_text="Provide detailed description of the incident day's events.", max_length=250),
        ),
        migrations.AddField(
            model_name='suspectresponse',
            name='query2',
            field=models.CharField(default='', help_text='Any motive for dishonesty about the incident? Please elaborate if applicable.', max_length=250),
        ),
        migrations.AddField(
            model_name='suspectresponse',
            name='query3',
            field=models.CharField(default='', help_text='Have you heard of any additional complaints filed by the accuser? If so, specify.', max_length=250),
        ),
        migrations.AddField(
            model_name='suspectresponse',
            name='question1',
            field=models.CharField(default='', help_text='Can you describe what happened on the incident day providing as many details as possible', max_length=250),
        ),
        migrations.AddField(
            model_name='suspectresponse',
            name='question2',
            field=models.CharField(default='', help_text='Can you think of any reason why someone would lie about this incident ? If yes, explain.', max_length=250),
        ),
        migrations.AddField(
            model_name='suspectresponse',
            name='question3',
            field=models.CharField(default='', help_text='Are you aware of any other complaints made by the accuser ? If yes, State.', max_length=250),
        ),
    ]
