# Generated by Django 4.2.7 on 2024-03-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0003_suspectresponse_query1_suspectresponse_query2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgenumber',
            name='email_address',
            field=models.EmailField(default=' ', help_text='Enter a valid Email Address', max_length=200),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=' ', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='peace.badgenumber')),
            ],
        ),
    ]
