# Generated by Django 4.2.7 on 2024-03-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0004_badgenumber_email_address_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='last_name',
        ),
        migrations.AddField(
            model_name='casecollection',
            name='case_victim',
            field=models.CharField(default=' ', help_text='Enter a valid Case Victim', max_length=200),
        ),
        migrations.AddField(
            model_name='suspect',
            name='suspect_name',
            field=models.CharField(default=' ', help_text='Enter Full Suspect Name', max_length=200),
        ),
    ]
